# PostgreSQL. Versions 9.3 and up are supported.
#

# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres   
  password: qwe
  localhost: 127.0.0.1:3000



development:
  <<: *default
  database: RsBlog_development



test:
  <<: *default
  database: RsBlog_test


production:
  <<: *default
  database: RsBlog_production
  username: postgres
  password: qwe
  localhost: 127.0.0.1:3000
